version: '3'

services:
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: 'apache/couchdb:${DOCKER_TAG:-latest}'
    environment:
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
    volumes:
      - './repos/couchdb:/opt/couchdb/data'
    ports:
      - 5984:5984
  dev:
    build: .
    ports:
      - 7070:7070
    volumes:
      - ./dist:/usr/src/app/dist
      - ./repos:/repos
      - ./src:/usr/src/app/src
    environment:
      NODE_ENV: production
      GITHUB_APP_ID: 34512
      GITHUB_WEBHOOK_SECRET: VietBible
      GITHUB_APP_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEoQIBAAKCAQEAwmuopwLIMIrY8pBCArXgrgBLuFvddUKh80q5sLY5ewP53uGF
        xvBDoLafMLB09NiQhFjirpQLH1lwSLbcnmzKchUUjlVCFWEgNP/gn0p6PubN4BZi
        QGifAQlu8F0AAshDe1UbAbe2S7NivLc17ifvdhKaeCUU+uSGmHS+MhltoSMimogU
        C9Jah94YAAxHJ9de6I/rDyxzNk8vSB2qP993fmazpKVy6t32mjK4Kcigv45H/R39
        FMHoIlF5urPN2NwU0GuEmmpqNWhKfQIcZob2hWMoBbUpa5kq6iGAbXMFDR8Le91N
        YXXGXig6keZ/LG+tCMv9uR99XuytUiKBmtaCCwIDAQABAoIBAHxitocLX5q26m/d
        3W2wgSuxosAzfe8Mj2KBN2YYX5QViiKPdLA/fXTwAc77xgf0GhmiaHy62JbY+N58
        p49wGOF+HSWm5F2bQyjFYCdpVeaycZrhl0CP7tKR/3kmduBQ0eOxIlMp/yZVgWEt
        cgKJaEnJQyyExPRziq01W43f+OSy4CAW8TM5I479jmYp67S9KkxPnP1X9TXkuV1L
        x7IRzTtpRRWtfxso9pobMwfW5FxWFOOas0C2Tl2M9LmyiAXP9fl0zalCeNMUltww
        gQ/AB4a0YLXn5ps8r6lLv4rtMXVVkxhfDyILWRgGIR2LqwyrCrs7VYHvBOyb93fu
        k0HVUXECgYEA9a6d4YOrfg5JrvA+50tWLRdSe92San844bRemnlwh/sxvKwMpA49
        a2ufb8eZlXW4tXZuMsy2bTnD1Iaed4YIT91XXR66oRlBcCn+tsN9u/wK1UzP3NQc
        1OaFiz5MuUwsR11Gty/vk9SUzUQfwwnlVOygkb8ZXVX14V0O/AYswqMCgYEAypXq
        6PPmkJ5gkmLH7EkB4Zl/K8t0vOdCqImieCaM1Spt0qGQkR5PcFqK7GQNczjSTGS6
        5aTez7WbRwC9eUtJdh478xW5FwaXK8rHF0OsOiKZ6zHUtQ6Y5f7ZuPqvpnw2Mwod
        h1gXECxMxcgNvSoqatP4kfa8ZTBYd4SfsSwCoXkCgYEAtuL/4Gp19OaJ71IkYWVx
        hyt/WXm9js2Z+FqeufuAy5kwkzS4TD/VdOuuyjUZnWr+zwaUTfiaLID9yG1V9b+u
        3FT2vfksENSOJAL+++pW5ONg5RvC+K5lsA7Shq8fyihsJcvH4oIqpC9xfcQiqLvr
        HebwOM67AQIGgXcWuoGWPGUCf33SnxQQaCNqOpCwyXr33TNBIrsQonCxMbV7xmzZ
        hJ7gu1UXA7MeIDioA6DOg4wMvpCz/2CiBcD8CnUPAJ9VI0s5fAJ+e3bRoRKR3xWT
        8mQpGW/6gyHw7wXqQ0+gY3gDraYFolFtZOWmngg5OE9E4RN4k+oUVO6EGG4i8QwZ
        SYkCgYB6itvYQhSj58+iiAMaLuzEHGRmMhDHbOsWdKAjjOSviLWNy1SYP6FjSwAW
        7gJUveNuvrk36W4iKkJlTsSTKIpEBizJvBJWpIVivJFbpvC+qnK1ejIXyfJp0Fkr
        XyL1xIMEMCysQ2XQDosxb1EMLUNg7VYVas16j6I1Arx1BPHOTQ==
        -----END RSA PRIVATE KEY-----
      LISTEN_REPOS: vgmtv/vb-md
      PRISMA_ENDPOINT: ${PRISMA_ENDPOINT}
      PRISMA_MANAGEMENT_API_SECRET: ${PRISMA_MANAGEMENT_API_SECRET}
    command: dev:docker
volumes:
  repos:
